# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kaffeinated Kodemonkey
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  HB21-1110 & ADA compliance audits for CO gov & edu. DHS Trusted Tester certified. Get your POCC to avoid fines. Free consultation!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kaffeinatedkodemonkey.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter: https://x.com/kfn8dKodeMonkey
github:  https://github.com/Kaffeianted-Kodemonkey
linkedIn: https://www.linkedin.com/in/kaffeinatedkodemonkey/
A11yDev: Heather Welsh
TTID: TT-2311-03604

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin

jekyll_admin:
  hidden_links:
    #- posts
    #- pages
    - staticfiles
    - datafiles
    - configuration

category-list: [Services, Policies, ADA-Compliance]

permalink: /:categories/:title/

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
